version: "3.9"

services:
  go-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celeb_go_backend
    ports:
      - "8080:8080"
    depends_on:
      - python-service
    environment:
      - PYTHON_SERVICE_URL=http://python-service:5000

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    container_name: celeb_python_service
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: celeb_frontend
    ports:
      - "3000:80"
    depends_on:
      - go-backend
      - python-service
